import {
    FaReact,
    FaNodeJs,
    FaPython,
    FaFigma,
} from "react-icons/fa";
import img from '@/public/assets/img-card.jpg';

export const courses = [
    {
        id: 1,
        title: "React.js من الصفر للاحتراف",
        slug: "react-js-course",
        category: "Frontend",
        image: img,
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        instructor: "محمد أحمد",
        lessons: 42,
        duration: "18 ساعة",
        level: "متقدم",
        price: 799,
        oldPrice: 999,
        rating: 4.9,
        students: 1250,
        featured: true,
        icon: FaReact,
        badge: "الأكثر مبيعًا",
        badgeColor: "bg-red-500",
    },
    {
        id: 2,
        title: "Node.js & Express",
        slug: "nodejs-express-course",
        category: "Backend",
        image: img,
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        instructor: "أحمد علي",
        lessons: 36,
        duration: "15 ساعة",
        level: "متوسط",
        price: 699,
        oldPrice: 899,
        rating: 4.8,
        students: 980,
        featured: true,
        icon: FaNodeJs,
        badge: "الأكثر مبيعًا",
        badgeColor: "bg-red-500",
    },
    {
        id: 3,
        title: "Python للمبتدئين",
        slug: "python-course",
        category: "Programming",
        image: img,
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        instructor: "سارة محمد",
        lessons: 30,
        duration: "12 ساعة",
        level: "جديد",
        price: 599,
        oldPrice: null,
        rating: 4.7,
        students: 760,
        featured: true,
        icon: FaPython,
        badge: "جديد",
        badgeColor: "bg-cyan-500",
    },
    {
        id: 4,
        title: "أساسيات UI/UX Design",
        slug: "ui-ux-course",
        category: "Design",
        image: img,
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        instructor: "نور علي",
        lessons: 28,
        duration: "10 ساعات",
        level: "مبتدئ",
        price: 499,
        oldPrice: null,
        rating: 4.9,
        students: 620,
        featured: true,
        icon: FaFigma,
        badge: null,
        badgeColor: "",
    },
    {
        id: 5,
        title: "أساسيات UI/UX Design",
        slug: "ui-ux-course",
        category: "Design",
        image: img,
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        instructor: "نور علي",
        lessons: 28,
        duration: "10 ساعات",
        level: "مبتدئ",
        price: 499,
        oldPrice: null,
        rating: 4.9,
        students: 620,
        featured: true,
        icon: FaFigma,
        badge: null,
        badgeColor: "",
    },
    {
        id: 6,
        title: "أساسيات UI/UX Design",
        slug: "ui-ux-course",
        category: "Design",
        image: img,
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        instructor: "نور علي",
        lessons: 28,
        duration: "10 ساعات",
        level: "مبتدئ",
        price: 499,
        oldPrice: null,
        rating: 4.9,
        students: 620,
        featured: true,
        icon: FaFigma,
        badge: null,
        badgeColor: "",
    },
];