const express = require("express");

const authRoutes = require("../modules/auth/auth.routes");
const serviceRoutes = require("../modules/services/service.routes");
const portfolioRoutes = require("../modules/portfolio/portfolio.routes");
const teamRoutes = require("../modules/team/team.routes");
const partnerRoutes = require("../modules/partners/partner.routes");
const categoryRoutes = require("../modules/category/category.route");
const courseRoutes = require("../modules/course/course.routes");
const courseDetailsRoutes = require("../modules/course-details/course-details.routes");
const lessonRoutes = require("../modules/lesson/lesson.routes");
const progressRoutes = require("../modules/progress/progress.routes");
const userRoutes = require("../modules/users/user.routes");
const productsRoutes = require("../modules/products/product.routes");
const couponRoutes = require("../modules/coupon/coupon.routes");
const cartRoutes = require("../modules/cart/cart.routes");
const orderRoutes = require("../modules/order/orders.routes");
const enrollmentRoutes = require("../modules/enrollment/enrollment.routes");
const reviewRoutes = require("../modules/review/review.route");
const wishlistRoutes = require("../modules/wishlist/wishlist.route");
const settingsRoutes = require("../modules/settings/settings.routes");
const dashboardRoutes = require("../modules/dashboard/dashboard.routes");
const heroRoutes = require("../modules/hero/hero.routes");
const blogRoutes = require("../modules/blog/blog.routes");
const contactRoutes = require("../modules/contact/contact.routes");
const journeyRoutes = require("../modules/journey/journey.routes");
const timelineRoutes = require("../modules/timeline/timeline.routes");
const chooseRoutes = require("../modules/choose-us/choose.route");

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/services", serviceRoutes);
router.use("/portfolios", portfolioRoutes);
router.use("/team", teamRoutes);
router.use("/partners", partnerRoutes);
router.use("/categories", categoryRoutes);
router.use("/courses", courseRoutes);
router.use("/course", courseDetailsRoutes);
router.use("/lessons", lessonRoutes);
router.use("/progress", progressRoutes);
router.use("/users", userRoutes);
router.use("/products", productsRoutes);
router.use("/coupons", couponRoutes);
router.use("/cart", cartRoutes);
router.use("/orders", orderRoutes);
router.use("/enrollments", enrollmentRoutes);
router.use("/reviews", reviewRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/settings", settingsRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/heroes", heroRoutes);
router.use("/blogs", blogRoutes);
router.use("/contact", contactRoutes);
router.use("/journey", journeyRoutes);
router.use("/timeline", timelineRoutes);
router.use("/choose", chooseRoutes);

module.exports = router;