import courseImage from "@/public/assets/img-card.jpg";

export const courses = [
    {
        id: 1,
        title: "Frontend Development Bootcamp",
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        category: "Frontend",
        level: "Beginner",
        duration: "12 Weeks",
        lessons: 48,
        students: 1250,
        rating: 4.9,
        price: 199,
        image: courseImage,
        featured: true,
    },
    {
        id: 2,
        title: "Advanced React.js",
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        category: "Frontend",
        level: "Intermediate",
        duration: "8 Weeks",
        lessons: 36,
        students: 820,
        rating: 4.8,
        price: 149,
        image: courseImage,
        featured: false,
    },
    {
        id: 3,
        title: "Node.js & Express API",
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        category: "Backend",
        level: "Intermediate",
        duration: "10 Weeks",
        lessons: 42,
        students: 930,
        rating: 4.9,
        price: 179,
        image: courseImage,
        featured: true,
    },
    {
        id: 4,
        title: "UI / UX Design",
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        category: "Design",
        level: "Beginner",
        duration: "6 Weeks",
        lessons: 24,
        students: 640,
        rating: 4.7,
        price: 99,
        image: courseImage,
        featured: false,
    },
    {
        id: 5,
        title: "Flutter Mobile Apps",
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        category: "Mobile",
        level: "Advanced",
        duration: "12 Weeks",
        lessons: 50,
        students: 510,
        rating: 4.8,
        price: 229,
        image: courseImage,
        featured: true,
    },
    {
        id: 6,
        title: "Python for Beginners",
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        category: "Programming",
        level: "Beginner",
        duration: "8 Weeks",
        lessons: 32,
        students: 1800,
        rating: 4.9,
        price: 89,
        image: courseImage,
        featured: false,
    },
    {
        id: 7,
        title: "Python for Beginners",
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        category: "Programming",
        level: "Beginner",
        duration: "8 Weeks",
        lessons: 32,
        students: 1800,
        rating: 4.9,
        price: 89,
        image: courseImage,
        featured: false,
    },
    {
        id: 8,
        title: "Python for Beginners",
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        category: "Programming",
        level: "Beginner",
        duration: "8 Weeks",
        lessons: 32,
        students: 1800,
        rating: 4.9,
        price: 89,
        image: courseImage,
        featured: false,
    },
    {
        id: 9,
        title: "Python for Beginners",
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        category: "Programming",
        level: "Beginner",
        duration: "8 Weeks",
        lessons: 32,
        students: 1800,
        rating: 4.9,
        price: 89,
        image: courseImage,
        featured: false,
    },
    {
        id: 10,
        title: "Python for Beginners",
        description:
            "تعلم React.js من الصفر حتى الاحتراف مع تطبيقات عملية ومشاريع حقيقية.",
        category: "Programming",
        level: "Beginner",
        duration: "8 Weeks",
        lessons: 32,
        students: 1800,
        rating: 4.9,
        price: 89,
        image: courseImage,
        featured: false,
    },
];